### ISSUE TITLE
jinja2::MakeCallable has compilation error when number of arguments > 3

### ISSUE THREAD

**Issue by linuxpham** [jinja2cpp/Jinja2Cpp#163]
**Example :**
oTemplateEnv->AddGlobal("urlize", jinja2::MakeCallable(
                                              [](const std::string &urlLink, const std::string &labelName, const int &limitWord, const std::string &targetStr) {
                                                  return urlLink;
                                              },
                                              jinja2::ArgInfo{"urlLink"}, jinja2::ArgInfo{"labelName"}, jinja2::ArgInfo{"limitWord", false, 0}, jinja2::ArgInfo{"targetStr", false, ""}));

Compile: g++: internal compiler error: Killed (program cc1plus)

**Comment by flexferrum** [comment]
Does the replacement with signature: `(const std::string &urlLink, const std::string &labelName, int64_t limitWord, const std::string &targetStr)` solves the problem?

**Comment by linuxpham** [comment]
I compile a very long time. BUT, this error still displays ^_^

**Comment by linuxpham** [comment]
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by flexferrum** [comment]
I have to chech but can't do it right now.

**Comment by linuxpham** [comment]
What version of g++ do you use?

**Comment by flexferrum** [comment]
According to this test: https://github.com/jinja2cpp/Jinja2Cpp/blob/fff06d6f53af44699058c541c4a1b80c898d5bea/test/user_callable_test.cpp#L173

Params with `int64_t` type should work. It needs some time to investigate the problem with your particular case. Regarding to the gcc version, the build matrix includes gcc versions range 5.4 - 9.0

**Comment by linuxpham** [comment]
Hi Admin,
If the length of the parameters is 1, it works. In my case, the length is 4, the compile had the issue ( g++: internal compiler error).
You should check in this case.
Thanks!

**Comment by flexferrum** [comment]
I've got the same error with VS2017 compiler. Investigation shown that the root of the problem is in the current UserCallable invoker implementation. It tries to find all combination of possible `Value` types and lambda parameters types which causes templates instantiation bloat. That's why compilation with gcc ends with segfalut and VS2017 compiler shows the heap problem.

**Comment by flexferrum** [comment]
Since the fix this problem has got three possible solutions:

1. You can explicitly specify type of lambda params with the special form of `ArgInfo`:
```
oTemplateEnv->AddGlobal("urlize", MakeCallable([](auto& urlLink, auto& labelName, auto limitWord, auto& targetStr) { return urlLink; },
                   jinja2::ArgInfoT<const std::string&>{ "urlLink" },
                   jinja2::ArgInfoT<const std::string&>{ "labelName" },
                   jinja2::ArgInfoT<int>{ "limitWord", false, 0 },
                   jinja2::ArgInfoT<const std::string&>{ "targetStr", false, "" }
));
```
In this case the template parameter of `ArgInfoT` is an actual type of the corresponding parameter of the lambda.

2. Replace lambda with pointer to the free or member function as in shown here: https://github.com/jinja2cpp/Jinja2Cpp/blob/69476050b7d71aa68216cc039e73e7b5159aab45/test/user_callable_test.cpp#L153

In any case you avoid template instantiations bloat by providing explicit information about user-defined callable parameters type.

**Comment by linuxpham** [comment]
You are very professional! Thanks so much!

**Comment by flexferrum** [comment]
You are welcome! :)
