### ISSUE TITLE
Use json as parameters input

### ISSUE THREAD

**Issue by Joe-Yeh** [jinja2cpp/Jinja2Cpp#78]
use json document object like rapidjson or nlohman as parameters input

**Comment by aletschhorn** [comment]
This would really be a great feature, just like also available in https://github.com/pantor/inja !

**Comment by flexferrum** [comment]
> This would really be a great feature, just like also available in https://github.com/pantor/inja !

The work is in progress.

**Comment by flexferrum** [comment]
JSON libraries to support:

- [ ] json for modern cpp ( https://github.com/nlohmann/json )
- [ ] rapid json ( https://github.com/Tencent/rapidjson )

**Comment by ludekvodicka** [comment]
It's great as additional input, but a bad idea to use nlohmann as core storage (as used in inja). Although nlohmann is a great library, it's slow. And because inja is using it as storage for everything, it's slowing down a whole library ;-(

**Comment by flexferrum** [comment]
Internal storage is based on fast (one of the fastest) hash map implementation and disconnected from external data representation as much as possible. So, scope of this issue is limited to front-end adapters which map json structure into internal maps representation. Like `reflection` feature already does.
