### ISSUE TITLE
proper installation

### ISSUE THREAD

**Issue by Nic30** [jinja2cpp/Jinja2Cpp#95]
Hello,

I see you are using Find*.cmake file to search this library.
https://github.com/flexferrum/Jinja2Cpp/blob/master/cmake/public/FindJinja2Cpp.cmake

Find*.cmake file is used for libraries which are **not**  build by the cmake.
The *Config.cmake is used for libraries which are build by cmake.
Or better you can use pkg-config.
https://stackoverflow.com/questions/17511496/how-to-create-a-shared-library-with-cmake

My problem is that the provided Find*.cmake does not work with meson build system, because it requires:
```
JINJA2CPP_INSTALL_DIR
```
which I can not add (meson uses cmake to discover the libraries).
(and is entirely against the Find file ideology btw.)

If the installation of you library was proper I would have worked.
Can you please fix the installation, maybe I can help but I do not have much time.

(
Using:

Jinja2Cpp 6193552 
cmake 3.12
meson  0.45.1
gcc 7.3.0
Ubuntu 18.04
and
Windows 10
VS2017
)

**Comment by Nic30** [comment]
Example of use of *Config.cmake https://github.com/pantor/inja/tree/master/cmake/config

**Comment by Nic30** [comment]
However there is still a problem. Dependencies (expected-lite  optional-lite  value-ptr-lite  variant-lite)
 are not installed at all and the library woks only as a cmake submodule.

This is a problem as it breaks the library entirely. However the cmake is not a package manager and thing should be solved by conan etc. Which package manager do you want to use?

**Comment by flexferrum** [comment]
Thanks for pointing that out.

> However there is still a problem. Dependencies (expected-lite optional-lite value-ptr-lite variant-lite)
are not installed at all and the library woks only as a cmake submodule.

Can you explain it in more details, please? Library shipped with `nonstd` libs as submodules. They should be updated automatically during the cmake scripts executing (in case of absence as external dependencies)

**Comment by Nic30** [comment]
They are downloaded but they are not part of "install" target so they stay only in directories where they were downloaded and are accessible for this build but are actually not installed in system.

**Comment by flexferrum** [comment]
Yeah. Now I see. It was removed in this commit:
https://github.com/flexferrum/Jinja2Cpp/commit/fa8aaeec8ee78f49544e5ce798bcd0b7d0dd627b#diff-af3b638bc2a3e6c650974192a53c7291

What is you try the latest release (0.9.1)?

**Comment by rmorozov** [comment]
@Nic30 There are several common attitudes
1. you build everything from source - and you use submodule approach - with versions of third parties that are chosen by lib author(not very flexible, because I may want to use boost 1.69, and jinja2cpp may bring me a version 1.65 that has known vulnerabilities)
2. you manually add all third party libs for project and finders inside jinja2 find prebuilt third parties. This way person who use jinja2cpp controls what version of boost and nonstd projects to pick up( quite flexible approach in general)
3. you use prebuilt versions from some common source, i.e. Conan, flexible as long as it doesn't bother you to have several different versions of the same library

If jinja2cpp ships headers from boost and nonstd within its installation it will cause problems for people who uses same libraries(boost, nonstd) but of other versions in their own project.

**Comment by flexferrum** [comment]
#102
